# Generated by Django 3.2.16 on 2023-03-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0036_reporttemplate_landscape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='host_detection_techniques',
            field=models.TextField(blank=True, help_text='Assign the difficulty of exploitation that fits: LOW, MEDIUM, HIGH', null=True, verbose_name='Difficulty of Exploit'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='mitigation',
            field=models.TextField(blank=True, help_text='Describe how this finding can be resolved or addressed', null=True, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='network_detection_techniques',
            field=models.TextField(blank=True, help_text='Assign a status of OPEN, ACCEPTED, or CLOSED to the finding', null=True, verbose_name='Status of Finding'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='replication_steps',
            field=models.TextField(blank=True, help_text='Provide a finding category that fits: Authentication, Authorization, Availability, Configuration Management, Encryption, Information Disclosure, Input Validation, Patch Management, or Session Management', null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='host_detection_techniques',
            field=models.TextField(blank=True, help_text='Assign the difficulty of exploitation that fits: LOW, MEDIUM, HIGH', null=True, verbose_name='Difficulty of Exploit'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='mitigation',
            field=models.TextField(blank=True, help_text='Describe how this finding can be resolved or addressed', null=True, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='network_detection_techniques',
            field=models.TextField(blank=True, help_text='Assign a status of OPEN, ACCEPTED, or CLOSED to the finding', null=True, verbose_name='Status of Finding'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='replication_steps',
            field=models.TextField(blank=True, help_text='Provide a finding category that fits: Authentication, Authorization, Availability, Configuration Management, Encryption, Information Disclosure, Input Validation, Patch Management, or Session Management', null=True, verbose_name='Category'),
        ),
    ]
